services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 8080:8080
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  